server:
  port: 8080
  servlet:
    contextPath: /api
spring:
  jpa:
    hibernate:
      ddl-auto: create
      
  datasource:
    url: jdbc:mysql://localhost:3306/isopcc_db
    username: root
    password: M@riaDB123